import { GAME_VERSION } from './gameActions';

export const INITIAL_STATE = {
    version: GAME_VERSION,
    characterName: '',
    characterClass: 'knight',
    level: 1,
    currentExp: 0,
    maxExp: 100,
    hp: 50,
    mp: 30,
    adena: 300000,
    inventory: [],
    baseStr: 0,
    baseDex: 0,
    baseCon: 0,
    baseInt: 0,
    baseWis: 0,
    allocatedStr: 0,
    allocatedDex: 0,
    allocatedCon: 0,
    allocatedInt: 0,
    allocatedWis: 0,
    equipment: {
        helm: null,
        armor: null,
        shirt: null,
        weapon: null,
        gloves: null,
        boots: null,
        cloak: null,
        shield: null,
        belt: null,
        necklace: null,
        ring_l: null,
        ring_r: null,
    },
    logs: [],
    combatLogs: [],
    currentMapId: 'village',
    sessionId: '',
    screenMessage: null,
    combatState: {
        isAttacking: false,
        attackFrame: 0,
        targetMonsterId: null,
        monsterHpPercent: 100,
        damageNumbers: [],
        respawnTimestamp: 0,
        potionEffect: null,
        impact: null,
    },
    lastRegenTime: 0,
    warehouse: [],
    sharedWarehouse: [],
    skillSlots: [null, null, null, null, null, null, null, null],
    autoSlotMask: [false, false, false, false, true, true, true, true],
    learnedSpells: [],
    elfElement: null,
    wizardDefaultSpell: null,
    friends: [],
    pendingAnnouncements: [],
    allCharacters: [],
    isCharacterSelected: false,
    party: null,
    partyInvite: null,
    partyBossConfirm: null,
};
